package com.example.smagionas.redbustickets;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.2.6.5
//
// Created by Quasar Development 
//
//---------------------------------------------------



public interface APTIServiceEvents
{
    public void Starting();
    public void Completed(APTOperationResult result);
}
