package com.example.smagionas.redbustickets;




//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.2.6.5
//
// Created by Quasar Development 
//
//---------------------------------------------------




import org.ksoap2.HeaderProperty;
import org.ksoap2.serialization.*;
import org.ksoap2.transport.*;
import org.kxml2.kdom.Element;

import java.lang.reflect.Constructor;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


public class APTMTRWebServiceSoap
{
    interface APTIWcfMethod
    {
        APTExtendedSoapSerializationEnvelope CreateSoapEnvelope() throws java.lang.Exception;

        java.lang.Object ProcessResult(APTExtendedSoapSerializationEnvelope __envelope,java.lang.Object result) throws java.lang.Exception;
    }

    String url="http://10.10.1.192/MTRWebSvc/MTRWebService.asmx";

    int timeOut=60000;
    public List< HeaderProperty> httpHeaders;
    public boolean enableLogging;

    APTIServiceEvents callback;
    public APTMTRWebServiceSoap(){}

    public APTMTRWebServiceSoap (APTIServiceEvents callback)
    {
        this.callback = callback;
    }
    public APTMTRWebServiceSoap(APTIServiceEvents callback,String url)
    {
        this.callback = callback;
        this.url = url;
    }

    public APTMTRWebServiceSoap(APTIServiceEvents callback,String url,int timeOut)
    {
        this.callback = callback;
        this.url = url;
        this.timeOut=timeOut;
    }

    protected org.ksoap2.transport.Transport createTransport()
    {
        try
        {
            java.net.URI uri = new java.net.URI(url);
            if(uri.getScheme().equalsIgnoreCase("https"))
            {
                int port=uri.getPort()>0?uri.getPort():443;
                return new HttpsTransportSE(uri.getHost(), port, uri.getPath(), timeOut);
            }
            else
            {
                return new HttpTransportSE(url,timeOut);
            }

        }
        catch (java.net.URISyntaxException e)
        {
        }
        return null;
    }
    
    protected APTExtendedSoapSerializationEnvelope createEnvelope()
    {
        APTExtendedSoapSerializationEnvelope envelope= new APTExtendedSoapSerializationEnvelope(APTExtendedSoapSerializationEnvelope.VER11);
            return envelope;
    }
    
    protected java.util.List sendRequest(String methodName,APTExtendedSoapSerializationEnvelope envelope,org.ksoap2.transport.Transport transport  )throws java.lang.Exception
    {
        return transport.call(methodName, envelope, httpHeaders);
    }

    java.lang.Object getResult(java.lang.Class destObj,java.lang.Object source,String resultName,APTExtendedSoapSerializationEnvelope __envelope) throws java.lang.Exception
    {
        if(source==null)
        {
            return null;
        }
        if(source instanceof SoapPrimitive)
        {
            SoapPrimitive soap =(SoapPrimitive)source;
            if(soap.getName().equals(resultName))
            {
                java.lang.Object instance=__envelope.get(source,destObj,false);
                return instance;
            }
        }
        else
        {
            SoapObject soap = (SoapObject)source;
            if (soap.hasProperty(resultName))
            {
                java.lang.Object j=soap.getProperty(resultName);
                if(j==null)
                {
                    return null;
                }
                java.lang.Object instance=__envelope.get(j,destObj,false);
                return instance;
            }
            else if( soap.getName().equals(resultName)) {
                java.lang.Object instance=__envelope.get(source,destObj,false);
                return instance;
            }
       }

       return null;
    }

        
    public String GetWebServiceURL(final String customerKey,final String licenseKey ) throws java.lang.Exception
    {
        return (String)execute(new APTIWcfMethod()
        {
            @Override
            public APTExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              APTExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://maimuri.org/", "GetWebServiceURL");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://maimuri.org/";
                __info.name="customerKey";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(customerKey!=null?customerKey:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://maimuri.org/";
                __info.name="licenseKey";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(licenseKey!=null?licenseKey:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(APTExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object obj = __soap.getProperty("GetWebServiceURLResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return j.toString();
                }
                else if (obj!= null && obj instanceof String){
                    return (String)obj;
                }
                return null;
            }
        },"http://maimuri.org/GetWebServiceURL");
    }
    
    public android.os.AsyncTask< Void, Void, APTOperationResult< String>> GetWebServiceURLAsync(final String customerKey,final String licenseKey)
    {
        return executeAsync(new APTFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return GetWebServiceURL( customerKey,licenseKey);
            }
        },"GetWebServiceURL");
    }

    
    protected java.lang.Object execute(APTIWcfMethod wcfMethod,String methodName) throws java.lang.Exception
    {
        org.ksoap2.transport.Transport __httpTransport=createTransport();
        __httpTransport.debug=enableLogging;
        APTExtendedSoapSerializationEnvelope __envelope=wcfMethod.CreateSoapEnvelope();
        try
        {
            sendRequest(methodName, __envelope, __httpTransport);
            
        }
        finally {
            if (__httpTransport.debug) {
                if (__httpTransport.requestDump != null) {
                    android.util.Log.i("requestDump",__httpTransport.requestDump);    
                    
                }
                if (__httpTransport.responseDump != null) {
                    android.util.Log.i("responseDump",__httpTransport.responseDump);
                }
            }
        }
        java.lang.Object __retObj = __envelope.bodyIn;
        if (__retObj instanceof org.ksoap2.SoapFault){
            org.ksoap2.SoapFault __fault = (org.ksoap2.SoapFault)__retObj;
            throw convertToException(__fault,__envelope);
        }else{
            return wcfMethod.ProcessResult(__envelope,__retObj);
        }
    }
    
    protected < T> android.os.AsyncTask< Void, Void, APTOperationResult< T>>  executeAsync(final APTFunctions.IFunc< T> func, final String methodName)
    {
        return new android.os.AsyncTask< Void, Void, APTOperationResult< T>>()
        {
            @Override
            protected void onPreExecute() {
                callback.Starting();
            };
            @Override
            protected APTOperationResult< T> doInBackground(Void... params) {
                APTOperationResult< T> result = new APTOperationResult< T>();
                try
                {
                    result.MethodName=methodName;
                    result.Result= func.Func();
                }
                catch(java.lang.Exception ex)
                {
                    ex.printStackTrace();
                    result.Exception=ex;
                }
                return result;
            }
            
            @Override
            protected void onPostExecute(APTOperationResult< T> result)
            {
                callback.Completed(result);
            }
        }.execute();
    }
        
    protected java.lang.Exception convertToException(org.ksoap2.SoapFault fault,APTExtendedSoapSerializationEnvelope envelope)
    {
        org.ksoap2.SoapFault newException = fault;

        return newException;
    }
}


