package com.example.smagionas.redbustickets;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.2.6.5
//
// Created by Quasar Development 
//
//---------------------------------------------------



public class APTOperationResult< T>
{
    public java.lang.Exception Exception;
    public T Result;
    public java.lang.Object Tag;
    public java.lang.String MethodName;
}
